import { readFile, readdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { format, resolveConfig } from 'prettier'

const newsDirectory = new URL('../src/data/news/', import.meta.url)
const indexPath = new URL('index.ts', newsDirectory)
const files = (await readdir(newsDirectory)).filter((file) => file.endsWith('.json')).sort()

for (const file of files) {
  if (!/^\d{4}-\d{2}-\d{2}\.json$/.test(file)) {
    throw new Error(`News files must use a YYYY-MM-DD.json name: ${file}`)
  }
}

const articles = files.map((file) => ({ file, name: `article${file.slice(0, 10).replaceAll('-', '')}` }))
const source = [
  '// Generated by pnpm news:generate. Do not edit manually.',
  ...articles.map(({ file, name }) => `import ${name} from './${file}' with { type: 'json' }`),
  "import type { NewsArticle } from '../techNews'",
  '',
  `export const newsArticles: NewsArticle[] = [${articles.map(({ name }) => name).join(', ')}]`,
  '',
].join('\n')
const indexFile = fileURLToPath(indexPath)
const formattedSource = await format(source, { ...(await resolveConfig(indexFile)), filepath: indexFile })

const current = await readFile(indexPath, 'utf8').catch((error: NodeJS.ErrnoException) => {
  if (error.code !== 'ENOENT') throw error
  return ''
})

if (current !== formattedSource) {
  await writeFile(indexPath, formattedSource)
  console.log(`Updated news index with ${articles.length} article(s)`)
}
